# INTRODUCTION {#introduction}

Clinical and epidemiologic studies have uniformly demonstrated that cardiovascular disease (CVD) risk is independently associated with both high concentrations of LDL-C and low concentrations of HDL-C [@assmann2004hdl; @barter2007hdl]. Particularly in patients with obesity and/or metabolic syndrome (MetS) low HDL-C is an independent risk factor for CVD [@bays2013obesity]. There is a strong body of evidence indicating that HDL-C concentrations are protective against CVD across populations, however, some recent trials show no benefit or even negative associations with higher HDL-C (reviewed in [@marz2017hdl]), and pharmaceutical interventions to increase HDL-C initially failed to demonstrate benefit in cardiovascular endpoints despite raising HDL-C concentrations [@schwartz2012effects; @aim2011niacin] though subsequent trials with improved drugs showed a benefit [@hps32017effects]. HDL particles are heterogeneous, with multiple subclasses and biologic functions, and undergo significant remodeling in vivo [@asztalos2011metabolic]. In fact, chemical, compositional, and structural changes can transform atheroprotective HDL into pro-atherogenic, pro-inflammatory particles [@ansell2007paradox]. Focus has shifted toward assessing the impact of various interventions on the composition and function of HDL particles and not just the absolute concentration of HDL-C in the blood.

Lipidomics studies have been performed to elucidate the molecular basis of HDL and its role in diseases including type 2 diabetes (T2D), dyslipidemia, and CVD [@staahlman2013dyslipidemia; @pruzanski2000comparative; @camont2013small]. Dietary factors have been shown to affect HDL composition and function; moderate carbohydrate restriction with egg consumption improved HDL cholesterol efflux capacity [@andersen2013egg], and fruits and vegetables improved whereas saturated fat and refined carbohydrates reduced HDL anti-inflammatory capacity (reviewed in [@andersen2013dietary]). Although different HDL protein and lipid components have different turn-over rates, the half-life of ApoA-I, the main protein constituent of HDL, is approximately 4 days [@thompson1988modest]. The effects of dietary changes on HDL lipidomic composition at this time scale have not been studied. Short-term dietary interventions could potentially be useful as clinical tools to assess individual responsiveness to diet. In addition, if substantial changes occur to the HDL lipidome within this short time frame of several days in response to diet, it is imperative to assess the extent of this influence to inform how frequently and closely diet must be controlled and monitored in longer-term intervention studies to minimize confounding effects.

In this pilot study, we hypothesized that a 4-day dietary intervention period measurably alters HDL lipidomic composition. We investigated the short-term effects of two different dietary patterns. The fast food (FF) diet, or the Western diet, which is enriched in red meat, simple sugars, fat, saturated fat, and cholesterol, and low in fresh fruits, vegetables and fiber [@bahadoran2012fast; @deng2017association; @garcia-arellano2015dietary; @oneil2015proinflammatory; @nettleton2006dietary], was compared to the Mediterranean (Med) diet, which is enriched in fresh fruits, vegetables, fiber, monounsaturated and polyunsaturated fat, particularly omega-3 fatty acids [@estruch2010anti-inflammatory; @estruch2013primary; @martinezlapiscina2013mediterranean; @salassalvado2011reduction; @salassalvado2008effect; @serramajem2006scientific]. HDL lipidomic composition in response to the two dietary patterns was assessed and compared.
