# MATERIALS AND METHODS {#methods}

## Subjects

Ten healthy human subjects (5 male and 5 female) were recruited from the community in Davis, CA. Subjects were 18-25 years old, non-smokers, with BMI 21.2-32.9 kg/$m^2$, and currently consuming fast food 3 times per week or less. Subjects with anemia, diabetes, thyroid disease, MetS, cancer, previous cardiovascular events or other disease diagnoses were excluded. Subjects were also excluded if they had extreme dietary or exercise patterns, or were taking prescription medications or other supplements known to alter lipoprotein metabolism such as isoflavones. The study was approved by the University of California Davis Institutional Review Board and the study followed all of the ethical standards of the Helsinki declaration. The study is registered at clinicaltrials.gov under identifier NCT03205254.

## Study design

Subjects were phone screened, consented, and enrolled in the study if they met all inclusion and exclusion criteria. In this randomized, cross-over study, each subject was randomized to intervention order using a randomized block design to either start on the FF or Med diet and cross over to the Med or FF diet, respectively, after the washout period. All treatment periods were 4 days in duration. All study food was provided to the subjects, either by purchasing from a local grocery store (Med) or fast food restaurants (FF). The study dietary plan was designed to match each subject’s daily Calorie requirement based on the Harris-Benedict equation. Subjects were asked to keep their normal physical activity during study periods.

Anthropometric measurements, including height, weight, blood pressure, hip and waist circumference were taken at the first and last day of each study arm. A blood sample was collected by a licensed phlebotomist from the antecubital vein after an overnight fast on the first and the day after the last day of each study arm, and plasma or serum was separated within 1 hour of the blood draw. An aliquot of sample was sent to the University of California Davis Medical Center (UCDMC) for a lipid panel test, while the rest of the samples were immediately aliquoted and stored at -80°C before analysis.

## Diet

Breakfast was provided to the subjects on the FF arm, while for lunch and dinner, subjects were instructed on exactly what to purchase from a local fast food restaurant. On the Med arm, ingredients for all three meals were purchased from a local grocery store, portioned by the study team, and picked up by subjects. Subjects were asked to return to their normal diet during washout. On the FF arm, 1-2 frosted strawberry pop-tarts were given for breakfast, and different hamburgers with or without fries were assigned to subjects for lunch and dinner. The sizes of hamburgers and fries were assigned according to the calorie levels. Subjects also consumed soda ad libitum as part of their meals. On the Med arm, high fiber cereal in 1% milk with one small banana was given for breakfast. Lunch was made of a study salad with dressing and 1-2 servings of canned no salt tuna or chicken, while dinner was made of 1-2 servings of minestrone soup, 1-2 servings of multigrain blend, 1 serving of tomato basil marinara, and extra virgin olive oil (EVOO) adjusted to the calorie level. Almonds and other dried fruits and nuts were provided as snack between meals according to the prescribed Calorie level. The study diet menu for FF and Med at 2000 kcals/day level is shown in **Supplemental Table S1 and S2**.

## HDL isolation

HDL particles were isolated using a 2-step density based sequential flotation ultracentrifugation method modified from a previous study [@krishnan2017hdl]. Potassium Bromide (KBr) solutions of density 1.063 g/mL, 1.210 g/mL, and 1.340 g/mL were freshly prepared and verified using a portable densitometer (Mettler Toledo, Columbus, OH). For each sample 2.0 mL of plasma was adjusted to a density of 1.063 g/mL by adding concentrated KBr solution (d=1.340 g/mL). Adjusted plasma was then underlaid to KBr solution of 1.063 g/mL in an ultracentrifugation tube (OptiSeal, Beckman Coulter), followed by ultracentrifugation at 110,000 rpm for 3 hours and 10 minutes. Ultracentrifugation was performed on a Beckman Optima MAX-TL equipped with a TLA-110 fixed-angle rotor (Beckman Coulter) with a k factor of 13.04. The 2-mL supernatant containing chylomicrons, remnants, VLDL and LDL was removed, and the bottom layer containing the HDL fraction was further adjusted to a density of 1.21 g/mL by adding concentrated KBr solution (d=1.340 g/mL). The adjusted fraction was then underlaid to KBr solution of 1.21 g/mL in two separate ultracentrifugation tubes, followed by ultracentrifugation at 110,000 rpm for 3 hours and 20 minutes. One mL supernatant of HDL fraction from each tube was combined and dialyzed using Amicon Ultra-4, MWCO 10 kDa filter devices twice to remove the KBr. HDL was reconstituted in LC-MS water and kept at -80°C until analysis.

## HDL lipidomics

HDL complex lipids, including PC (phosphatidylcholine), PE (phosphatidylethanolamine), PG (lysophosphatidylcholine), LPE (lysophosphatidylethanolamine), SM (sphingomyelin), FA (fatty acid), TG (triacylglycerol), DG (diacylglycerol), MG (monoacylglycerol), FC (free cholesterol), and CE (cholesteryl ester) were measured at the West Coast Metabolomics Center, using the protocol described elsewhere [@cajka2016using]. 225 μL of cold methanol containing lipid internal standards (PE(17:0/17:0), PG(17:0/17:0), LPC(17:0), C17 sphingosine, C17 ceramide, SM(d18:1/17:0), palmitic acid (d3), PC(12:0/13:0), cholesterol (d7), TG(17:0/17:1/17:0) d5, DG(12:0/12:0), DG(18:1/2:0), MG(17:0), and LPE(17:1)) were added into 25 μL purified HDL sample, followed by adding 750 μL cold MTBE containing CE(22:1). After shaking at 4 °C for 6 minutes, 188 μL of distilled water was added, and the sample was centrifuged at 14,000 g for 2 minutes. 350 μL supernatant was extracted, dried down, and reconstituted with 65 μL methanol/toluene (9:1, v/v) solution. 3 μL of the reconstituted sample was then injected into a LCMS for analysis. Each sample was injected in parallel into an Agilent 6530 QTOF with positive mode, and an Agilent 6550 QTOF with negative mode, with the purpose of capturing as many complex lipid species as possible. LC separation was done on a Waters UPLC CSH C18 column (1.7 μm, 2.1 mm 100 mm), using a gradient method. A QC (quality control) sample was run every $\text{11}^{\text{th}}$ injection. The QC samples all came from the same human plasma pool.

## Lipidomics data processing

MS data was processed using MS-DIAL [@tsugawa2015ms]. Lipid species were identified through 2 methods. Liquid chromatogram retention time and MS1 m/z was searched against the in house rt-mz library [@cajka2016using]. The fragmentation pattern in MS2 was searched against the in silico library LipidBlast [@kind2013lipidblast]. Lipid species identified using rt-mz library are MSI level 3, and the ones identified through fragmentation pattern searching are MSI level 2 [@sumner2007proposed]. This method is able to identify lipid species in 14 lipid classes, including PC, PE, LPC, LPE, PG, CE, sphingosine, ceramide, SM, FA, FC, TG, DG, and MG. Quantification was done using a single-point, class specific calibration curve using internal standards, as shown below [@cajka2016using].
\begin{equation}
	\text{conc}_{\text{i,j}} = \frac{\text{int}_{\text{i,j}}}{\text{int}_{\text{k,j}}}\ \times\ \text{conc}_{\text{k}}
\end{equation}
Where the $\text{conc}_{\text{i,j}}$ is the concentration of lipid i in the sample j. $\text{int}_{\text{i,j}}$ is the intensity of lipid i in sample j. $\text{int}_{\text{i,k}}$ is the intensity of internal standard of lipid class k detected in sample j. $\text{conc}_{\text{k}}$ is the spiked concentration of internal standard for lipid class k.

## Statistical Analysis

The HDL lipidomic data were transformed to a proportion (mg %) for each species.
$$ \text{Proportion}_{\text{i,j}}\ =\ \frac{\text{conc}_{\text{i,j}}}{\sum_{\text{i=1}}^{\text{n}} \text{conc}_{\text{i,j}}} $$
The proportion of lipid species i in sample j equals to its concentration divided by the sum of the concentration of all the lipid species in sample j. The proportion of all species in the same lipid class were added up to get the proportion of each lipid class.

Lipidomics data were transformed and summarized to obtain the $\text{EOD}_{\text{18}}$ (equivalent of double bond per 18 carbons) and ACL (average chain length). The $\text{EOD}_{\text{18}}$ was calculated using the equation below:

$$\text{EOD}_{\text{18}}\ =\ \frac{\sum_{\text{i=1}}^{\text{n}}\ \text{conc}_{\text{i,j}}\ \times\ \text{ndb}_{\text{i,j}}}{\sum_{\text{i=1}}^{\text{n}}\ \text{conc}_{\text{i,j}}\ \times\ \text{nc}_{\text{i,j}}}\ \times\ \text{18} $$

$\text{conc}_{\text{i,j}}$ is the mol concentration of the $\text{j}^{\text{th}}$ lipid species in $\text{i}^{\text{th}}$ sample. $\text{ndb}_{\text{i,j}}$ is the number of double bonds of this lipid species, while $\text{nc}_{\text{i,j}}$ is the number of carbons. The ACL is calculated using the equation below:

$$\text{ACL}\ =\ \frac{\sum_{\text{i=1}}^{\text{n}}\ \text{conc}_{\text{i,j}}\ \times\ \text{nc}_\text{i}}{\sum_{\text{i=1}}^{\text{n}}\ \text{conc}_{\text{i,j}}\ \times\ \text{nfa}_\text{i}}$$

$\text{nfa}_{\text{i,j}}$ represents the number of fatty acids for the $\text{i}^{\text{th}}$ lipid species in the $\text{j}^{\text{th}}$ sample (for example, a PC or a DG will be 2, and a TG will be 3).

Several lipid class mole ratios were calculated including PC/LPC, CE/FC, SM/PL, and surface/core lipids. Surface lipids are amphipathic lipid classes including PC, PE, SM, Cer, LPC, cholesterol, and DG, while core lipids are hydrophobic lipids CE and TG. PL are total phospholipids, including PC, PE, SM, and LPC. Class specific OCFA (odd chain fatty acids) were calculated by summing up the mole concentration of all lipid species with odd number of carbons in the same lipid class.

A differential abundance test was applied to the normalized HDL lipidomic data using a mixed linear model, with the R package, limma [@ritchie2015limma]. Multiple test correction was performed on the p-values using the Benjamini-Hochberg method. Data were log2 transformed before differential abundance test and the shapiro.test function in R was used to perform Shapiro-Wilk test of normality. The Pearson’s correlation test was applied to find the correlation between different variables. Multiple testing correction was not applied to correlation analysis due to the  exploratory nature of this analysis. Compound similarity Tanimoto coefficient was calculated using the R package fmcsR [@Wang_2013] and ChemmineR [@Cao_2008]. The hierarchical clustering method was used to group lipid species that responded similarly across all samples. The hclust function in R’s stats package was used, followed by the cutree function setting the argument h equals to 8 to generate 32 clusters. The proportion data was z-score normalized prior to clustering. PCA analysis was performed using the prcomp function in R.
