# RESULTS {#results}

## Baseline Characteristics and Dietary Records

The baseline characteristics of the 10 subjects are listed in **Table 1**. All subjects were healthy with normal blood pressure and blood lipids levels. Neither the anthropometric nor the circulating lipid variables were significantly affected by the diets. The BMIs of all subjects were normal to slightly overweight. Summary data from the three-day diet records from baseline and during the two study treatments are listed in **Table 2**. The total calorie intake of each subject was relatively equivalent to their baseline level. The daily calorie intake at baseline was not significantly different from FF (p = 0.506) or Med (p=0.277). All subjects had significantly higher saturated fat (p < 0.0001), trans fat (p < 0.0001), protein (p = 0.0005) intake, and lower unsaturated fat (p < 0.0001) and fiber intake (p < 0.0001) on the FF diet arm compared to the Med diet **Table 2**. Carbohydrate intake was not significantly different between the two treatments.

## HDL Lipidome

With the lipidomics method, 170 lipid species in 9 different lipid classes were detected in 78 or more samples, with 167 of them were detected in all samples. **Supplemental Table S3** lists all lipid species with their relative abundance before and after FF and Med, as well as their linear mixed model p-values. According to the quality control samples, the average coefficient of variation (CV) of all the lipid species was 11.43 (± 6.58) %, with 90% of the lipid species having a CV < 20%  (**Fig.  \@ref(fig:lpd-class)-A&B**). The average composition of isolated HDL from this population across diet treatments was 46.2% CE, 29.4% PC, 9.7% FC, 6.8% TG, 5.2% SM, and 2.2% PE. The rest of the lipid classes including LPC, DG, and Ceramides added up to 0.5% of the total lipids (**Fig. \@ref(fig:lpd-class)-C**). At the lipid class level, HDL PE was significantly (p = 0.0003) elevated after FF but not Med (**Fig. \@ref(fig:lpd-class)-D**). All 170 lipid species are presented in the cladogram in **Fig. \@ref(fig:lpd-class)-E**. In the cladogram, lipids were clustered based on their structural similarity using the Tanimoto coefficient, which measures the structural similarity between chemical compounds [@nikolova2003approaches]. The cladogram also shows the change of each lipid species on FF and Med from baseline. It shows that more PC species increased after FF, and more TG species decreased after Med. The linear mixed model shows 65 out of 170 features were significantly and differently affected by FF and Med (p < 0.05, unadjusted, **Fig. \@ref(fig:lpd-class)-F**), and the significance remained for 41 lipid species after adjustment for multiple comparisons. The principal component analysis (PCA) and its loading plot shown in **Fig. \@ref(fig:lpd-class)-G&H** were drawn using the change from baseline on FF and Med diet of the 41 species with an adjusted p-value that was significant at p < 0.05. The PCA plot shows the lipidome changed differently on the FF compared with the Med diet, while the loading plots show that different lipid species were enriched on the two diets.

The changes of the 41 lipids species after FF and Med diet from baseline are presented in **Fig. \@ref(fig:lpd-species)-A**. Using the hierarchical clustering method, lipid species that showed similar response across study subjects and treatments clustered together (**Fig. \@ref(fig:lpd-species)-B**). The clustering method was able to form 32 clusters from the 170 lipid species, and 9 clusters were significantly altered after FF versus Med diet (p < 0.05, adjusted). PCs with long chain fatty acids (C16-20) and less double bonds were either elevated after FF or decreased after Med, including PC 30:0, PC 32:2, PC 34:0, 34:4, PC 36:2, and PC 36:4 (cluster 6, 8, and 28). PCs with very long chain fatty acids (C20-22) tended to increase after Med but not FF, including PC 40:6 and PC 40:7, which have more double bonds than the PC species that were elevated after FF (cluster 11). Plasmenyl PCs tended to increase after FF rather than Med, including PC 34:1 p, PC 34:2 p, PC 36:2 p, and PC 38:4 p (cluster 12). CE species were elevated after Med but not FF, including CE 18:1, CE 20:4, and CE 22:6 (cluster 20). SM species SM 34:2 and SM 42:3 (cluster 1) were decreased after FF and increased after Med. Several PE and plasmenyl PE species were also elevated after FF but not Med, including PE 36:2 p, PE 34:2 p, and PE 38:4 p (cluster 12).

## Lipidome Characteristics

In order to better understand the HDL lipidome, two descriptive variables, $\text{EOD}_{\text{18}}$ and ACL, were calculated from the lipidomic data as described above. The overall $\text{EOD}_{\text{18}}$ of the lipidome was 1.70 double bonds per 18 carbons, and the overall ACL was 18.14. Both the $\text{EOD}_{\text{18}}$ (p < 0.001, adjusted) and ACL (p = 0.001, adjusted) of PC significantly decreased after FF and increased after Med diet (**Fig. \@ref(fig:lpd-eod)-A&B**). CE had the highest $\text{EOD}_{\text{18}}$ (2.37) at the baseline level, followed by PE (2.00), and PC (1.44), while TG, SM, Ceramide, and LPC have very small $\text{EOD}_{\text{18}}$ (0.98, 0.74, 0.50, and 0.61) which suggests saturated fatty acids dominate these lipid classes. Lipid classes with a high $\text{EOD}_{\text{18}}$, including PE and CE, were significantly affected by the dietary interventions (p < 0.001 & p = 0.003, adjusted) as their double bonds decreased after FF and increased after Med. Overall TG, SM, Ceramide, and LPC have small $\text{EOD}_{\text{18}}$, and they were not significantly affected by either dietary treatment. The overall $\text{EOD}_{\text{18}}$ also decreased after FF and increased after Med. PE, PC, CE, and overall $\text{EOD}_{\text{18}}$ were also significantly correlated with dietary MUFA (PE: p < 0.001, R = 0.796; PC: p < 0.001, R = 0.651; CE: p = 0.017, R = 0.431; Overall: p = 0.037, R = 0.383. All p-values were unadjusted and all R values are Spearman’s correlation coefficients) and PUFA intake (PE: p < 0.001, R = 0.812; PC: p < 0.001, R = 0.700; CE: p = 0.014, R = 0.443; Overall: p = 0.025, R = 0.408.). 

Ceramides had the longest carbon chain length (19.06) at baseline, followed by PE (18.54), SM (18.53), CE (18.50), while DG, TG and LPC had less very long chain lipids (ACL=18.00, 17.35, and 17.12). The ACL of CE, PE, PC, TG and overall ACL were significantly altered by dietary interventions (p < 0.001, p = 0.001, 0.0012, and 0.0013, adjusted) as the fatty acyl length were decreased after FF and increased after Med.

Four lipid classes were detected with lipid species containing OCFAs (odd chain fatty acid), PC, SM, TG, and Cer. The OCFAs carried by PC and SM were at a similar level, but SM had the highest relative proportion of OCFAs (8.41%), followed by Cer (4.67%), TG (1.95%), while PC (1.55%) had the lowest relative proportion. PC OCFAs were significantly increased after FF and decreased after Med diet (p < 0.001, **Fig. \@ref(fig:lpd-eod)-C**). OCFAs in SM, TG, and Cer were not significantly affected by the diets (**Fig. \@ref(fig:lpd-eod)-D**). 

HDL surface lipids include all amphipathic phospholipids, sphingolipids, FC, mono- and di-acylglycerols. PC/LPC ratio was negatively associated with CE/FC ratio (rho = -0.506, p = 0.001, **Supplemental Fig. S1-A**). CE/FC ratio had a very high negative correlation with surface to core lipids ratio (rho = -0.846, p < 0.001, **Supplemental Fig. S1-B**).