# DISCUSSION {#discussion}

The Med diet was chosen for this study because it is known to improve cardiometabolic health and decrease disease risk from both epidemiological and intervention studies [@estruch2013primary; @esposito2004effect; @de1999mediterranean]. The FF diet was chosen because according to the CDC increasing numbers of Americans are consuming convenience and fast foods on a daily basis [@smith2013trends], and observational studies have found this type of diet to be associated with increased markers of inflammation and disturbed lipid profiles [@nettleton2006dietary]. Although the term “fast food” can be used to describe many different kinds of foods that are prepared quickly, in this study, the term was used to refer to the most “classic” American fast food meal including a burger, fries, and a soft drink purchased at a fast food restaurant. Although the long-term impact of the two diets to cardiometabolic health and lipid profile were well documented, no research studies reported their short-term effects in a time-scale similar to our study. Only one study directly compared the effects of a fast food style diet to a traditional German diet to a Med diet in 2 weeks with 39 healthy human subjects, and found very little difference in effects on a variety of cardiometabolic health parameters including LDL-C, HDL-C, TG, and homocysteine [@parcina2015no].

A few studies have specifically studied HDL lipidome composition at lipid species level. Weisner et al. developed a LCMS method that provided the pioneering reference to HDL lipidome on FPLC isolated HDL fractions [@wiesner2009lipid]. A study done by Andersen et al reported the PL, CE and free cholesterol proportion to be 46.0, 40.4, and 5.1 % (wt), respectively, in human subjects with MetS [@andersen2013egg], and Camont et al reported the three major HDL lipid classes in similar proportions [@camont2013small]. A study done by Sawrey-Kubicek et al. found reported more PC (36.3%), TG (13.9%) and SM (8.5%), and less CE (25.9%) in post-menopausal women [@sawrey-kubicek2019whole]. HDL lipidome composition was also reviewed by Kontush et al, with PC 33-45%, PE 0.5-1.5%, SM 5-10%, FC 5-10%, and CE 30-40% [@kontush2013unravelling]. In our study, the SM (5.2%) and FC (9.7%) contents fall into the range reported by Kontush et al [@kontush2013unravelling]. CE (46.2%) and PE (2.2%) contents were higher than reported, while PC (29.4%) was lower [@kontush2013unravelling]. HDL lipid composition varies depending on the particle size, and large HDL particles have higher CE and lower PC [@kontush2013unravelling]. It is possible that our study population, which included only young, healthy individuals, had more large HDL particles compared to populations from the previously published reports, thus more proportion of core lipids (e.g., CE) and less proportion of surface lipids (e.g., PC) were observed.

This is the first reported study investigating the impact of dietary change on the time scale of 4 days on HDL lipid composition in healthy human subjects. In a study examining the effects of a diet rich in n-3 fatty acids and polyphenols in overweight human subjects with high CVD risk, an increase in PC and TG enriched in n-3 FA was observed in both plasma and HDL after 8 weeks of intervention [@bondia2014isoenergetic]. In a study that compared the HDL lipidome of T2D patients, T2D patients with dyslipidemia, and healthy subjects, HDL SM was significantly lower in T2D patients with dyslipidemia [@staahlman2013dyslipidemia]. In the current study HDL SM was increased after the Med diet. Several TG species have previously been shown to be significantly higher in T2D patients with or without dyslipidemia compared to healthy controls [@staahlman2013dyslipidemia], and in our study were decreased after Med but not FF, including TG 48:1, TG 48:2, TG 48:3, and TG 52:1. In another study that looked at the long-term effect of fenofibrate therapy on HDL in CVD patients [@yetukuri2011high], the plasmalogen species PE 40:6 p (plasmalogen) and PE 38:5 p were decreased and SM 32:1 was increased in patients on fenofibrate. In this current study, PE 40:6 p and PE 38:5 p increased after FF, but not Med, and SM 32:1 increased after Med, but not FF.

Since the FF diet was rich in SFAs and the Med diet was rich in MUFAs, FA in several classes, especially PC and PE became shorter and had less double bonds after FF and were longer and had more double bonds after Med. However the ACL and $\text{EOD}_{\text{18}}$ of SM and ceramides were not affected by either treatment. In addition, although PC and SM carry similar amounts of OCFA, the OCFA content of PC but not SM increased after FF and decreased after Med. These observations suggests that compositional remodeling of phosphoglycerolipid FA is more sensitive to diet compared to phosphosphingolipids.

The strengths of this study include that all food intake during the study periods was provided and controlled; the consistent changes in specific lipid species across all subjects indicate that compliance with the diet was high; and a complex lipidomics method was applied to quantify each lipid species. A weakness of this study is the relatively small number of subjects. However, the study was a cross-over study and therefore each subject acted as their own control, increasing the power to detect changes in response to diet. The ultracentrifugation-based HDL isolation method was optimized to remove ApoB-containing lipoprotein and albumin as far as possible. However, the gel electophoresis (**Supplemental Fig. S2**) shows that there is still some albumin contamination. Hence, a more refined purification strategy including size exclusion chromatography after the ultracentrifugation step [@holzer2016refined], or other methods that minimize particularly albumin contamination may have been better.

In conclusion, 4-day dietary interventions feeding the FF diet and the Med diet differentially changed HDL lipidomic composition. Our results suggest that certain HDL lipids could be useful markers of short-term dietary intake (i.e. PC, PE, CE), whereas other HDL lipids (i.e. SM, ceramides) are not as responsive to short-term dietary change and may be more useful indicators of long-term intake as well as non-dietary factors and disease conditions. Our study has dedicated focus on HDL, hence it is not clear whether a similar pattern is applied to the plasma lipidome. Feature studies need to be done to evaluate the short-term dietary effect to plasma lipidome. These results have implications for studies comparing the plasma HDL lipidome of individuals with different disease conditions vs. controls, or in response to different treatments. Our findings suggest that certain lipid classes are very sensitive to dietary changes in the short term, making them excellent markers of short-term dietary intake, but potentially not very good candidates for the discovery of biomarkers of disease or other non-diet factors.
